### ISSUE TITLE
Cannot setup CrossPlatformLibrary.Device on UWP

### ISSUE THREAD

**Issue by ckogevina** [thomasgalliker/CrossPlatformLibrary.Device#1]
I use CrossPlatformLibrary for Device and Geolocation on a PCL project with Android, iOS and UWP and it has been really usefull.
In Android and iOS everything works perfectly. In UWP when I include CrossPlatformLibrary.Device I get the following error on UWP during bootstrapper.Startup(). I use the default bootstrapper, I have not created my own class. I installed CrossPlatformLibrary through nuget and on the UWP project I have the following packages included: 
  "CommonServiceLocator": "1.3.0",
    "CrossPlatformAdapter": "1.0.12",
    "CrossPlatformLibrary": "1.0.73",
    "CrossPlatformLibrary.Device": "1.0.12",
    "CrossPlatformLibrary.Geolocation": "1.0.25",
    "Guards": "1.0.11",
I'm not sure if I'm doing something wrong or it's just not implemented.

Debug - Initializing container extension CrossPlatformLibrary.Device.ContainerExtension.

Fatal - FatalError
System.AggregateException: One or more errors occurred. (Type CrossPlatformLibrary.Device.DeviceInfo which is supposed to implement CrossPlatformLibrary.Device.IDeviceInfo could not be resolved in assembly CrossPlatformLibrary.Device, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null.) (Type CrossPlatformLibrary.Device.DeviceInfo which is supposed to implement CrossPlatformLibrary.Device.IDeviceInfo could not be resolved in assembly CrossPlatformLibrary.Device.Platform, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null.) ---> CrossPlatformAdapter.Exceptions.PlatformSpecificTypeNotFoundException: Type CrossPlatformLibrary.Device.DeviceInfo which is supposed to implement CrossPlatformLibrary.Device.IDeviceInfo could not be resolved in assembly CrossPlatformLibrary.Device, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null.
   --- End of inner exception stack trace ---
   at CrossPlatformAdapter.ProbingAdapterResolver.DoResolveClassTypeUsingAllStrategies(Type interfaceType, Boolean throwIfNotFound)
   at CrossPlatformAdapter.ProbingAdapterResolver.ResolveClassType(Type interfaceType)
   at CrossPlatformLibrary.IoC.SimpleIoc.RegisterWithConvention[TInterface](IResolvedParameter[] resolvedParameters)
   at CrossPlatformLibrary.Device.ContainerExtension.Initialize(ISimpleIoc container)
   at CrossPlatformLibrary.Bootstrapping.Bootstrapper.ConfigureExtensions(IPlatformServices platformServices)
   at CrossPlatformLibrary.Bootstrapping.Bootstrapper.InternalConfigureExtensions()
---> (Inner Exception #0) CrossPlatformAdapter.Exceptions.PlatformSpecificTypeNotFoundException: Type CrossPlatformLibrary.Device.DeviceInfo which is supposed to implement CrossPlatformLibrary.Device.IDeviceInfo could not be resolved in assembly CrossPlatformLibrary.Device, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null.<---

---> (Inner Exception #1) CrossPlatformAdapter.Exceptions.PlatformSpecificTypeNotFoundException: Type CrossPlatformLibrary.Device.DeviceInfo which is supposed to implement CrossPlatformLibrary.Device.IDeviceInfo could not be resolved in assembly CrossPlatformLibrary.Device.Platform, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null.<---

Error - BootstrapperUnhandledException
System.AggregateException: One or more errors occurred. (Type CrossPlatformLibrary.Device.DeviceInfo which is supposed to implement CrossPlatformLibrary.Device.IDeviceInfo could not be resolved in assembly CrossPlatformLibrary.Device, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null.) (Type CrossPlatformLibrary.Device.DeviceInfo which is supposed to implement CrossPlatformLibrary.Device.IDeviceInfo could not be resolved in assembly CrossPlatformLibrary.Device.Platform, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null.) ---> CrossPlatformAdapter.Exceptions.PlatformSpecificTypeNotFoundException: Type CrossPlatformLibrary.Device.DeviceInfo which is supposed to implement CrossPlatformLibrary.Device.IDeviceInfo could not be resolved in assembly CrossPlatformLibrary.Device, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null.
   --- End of inner exception stack trace ---
   at CrossPlatformAdapter.ProbingAdapterResolver.DoResolveClassTypeUsingAllStrategies(Type interfaceType, Boolean throwIfNotFound)
   at CrossPlatformAdapter.ProbingAdapterResolver.ResolveClassType(Type interfaceType)
   at CrossPlatformLibrary.IoC.SimpleIoc.RegisterWithConvention[TInterface](IResolvedParameter[] resolvedParameters)
   at CrossPlatformLibrary.Device.ContainerExtension.Initialize(ISimpleIoc container)
   at CrossPlatformLibrary.Bootstrapping.Bootstrapper.ConfigureExtensions(IPlatformServices platformServices)
   at CrossPlatformLibrary.Bootstrapping.Bootstrapper.InternalConfigureExtensions()
---> (Inner Exception #0) CrossPlatformAdapter.Exceptions.PlatformSpecificTypeNotFoundException: Type CrossPlatformLibrary.Device.DeviceInfo which is supposed to implement CrossPlatformLibrary.Device.IDeviceInfo could not be resolved in assembly CrossPlatformLibrary.Device, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null.<---

---> (Inner Exception #1) CrossPlatformAdapter.Exceptions.PlatformSpecificTypeNotFoundException: Type CrossPlatformLibrary.Device.DeviceInfo which is supposed to implement CrossPlatformLibrary.Device.IDeviceInfo could not be resolved in assembly CrossPlatformLibrary.Device.Platform, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null.<---

Exception thrown: 'CrossPlatformLibrary.Bootstrapping.BootstrappingException' in CrossPlatformLibrary.dll

**Comment by thomasgalliker** [comment]
Hi ckogevina. Thank for your feedback. I just checked the UWP source code of CrossPlatformLibrary.Device and there is no implementation yet. Let me check tonight if I can implement DeviceInfo for UWP.

Lets keep this issue open as a reminder.

**Comment by ckogevina** [comment]
Thanks a lot for looking into it.

**Comment by thomasgalliker** [comment]
Can you check the latest pre-release of CrossPlatformLibrary.Device (which is 1.0.13-pre3 at the moment). Let me know if it works.

**Comment by ckogevina** [comment]
Hello,

just checked it. Works perfectly.
Thank you very much.

**Comment by thomasgalliker** [comment]
Great. I gonna release the stable version soon.
Just fyi: All cross-platform packages are going to be migrated to version 2.x soon, a "bait and switch" PCL project. Have fun doing apps!
